sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t sirmmo/rockstory_games-front .
      - docker push sirmmo/rockstory_games-front
 
notifications:
  slack:
    rooms:
      - ingmmo:SW0ahzRuwFIJKKAlQPzGRg0f#prj-coneja
      - ingmmo:SW0ahzRuwFIJKKAlQPzGRg0f#travisbuilds
